desc: "Xen-Troops development setup for Renesas RCAR Gen3 hardware"

variables:
  YOCTOS_WORK_DIR: "yocto"
  DOMD_BUILD_DIR: "build-domd"
  DOM0_BUILD_DIR: "build-dom0"
  XT_DOMD_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-domd.dtb"
  XT_DOMU_DTB_NAME: "salvator-generic-domu.dtb"
  XT_XEN_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-xen.dtb"
  XT_PVR_NUM_OSID: "2"
  XT_OP_TEE_FLAVOUR: "generic_dt"
common_data:
  # Common configuration options for all yocto-based domains
  sources: &COMMON_SOURCES
    - type: git
      url: "https://github.com/xen-troops/meta-xt-common.git"
  conf: &COMMON_CONF
    - [SSTATE_DIR, "${TOPDIR}/../common_data/sstate"]
    - [DL_DIR, "${TOPDIR}/../common_data/downloads"]

    # Skip warning about missing "virtualization" distro feature
    - [SKIP_META_VIRT_SANITY_CHECK, "1"]

    # Use hypervisor console on all guests
    - [SERIAL_CONSOLES, "115200;hvc0"]

    # Configure number of supported GPU virtual guests
    - [XT_PVR_NUM_OSID, "%{XT_PVR_NUM_OSID}"]

    # Remove features that we are not using
    - [DISTRO_FEATURES_remove, "x11 gtk gobject-introspection-data wifi nfc bluetooth irda zeroconf 3g sysvinit"]

  # Conf options for domain that are built used renesas layer
  domd_domu_conf: &DOMD_DOMU_CONF
    - [MACHINE, "%{MACHINE}"]
    - [SOC_FAMILY, "%{SOC_FAMILY}"]

    # Add systemd configuration
    - [DISTRO_FEATURES_append, " systemd"]
    - [VIRTUAL-RUNTIME_init_manager, "systemd"]

    # add the static lib to SDK toolchain
    - [SDKIMAGE_FEATURES_append, " staticdev-pkgs"]

    # Enable Gfx Pkgs
    - [MACHINE_FEATURES_append, " gsx"]
    - [MULTI_PROVIDER_WHITELIST_append," virtual/libgl virtual/egl virtual/libgles1 virtual/libgles2"]

    # for Wayland/Weston
    - [DISTRO_FEATURES_NATIVESDK_append, " wayland"]
    - [DISTRO_FEATURES_append, " pam"]
    - [PREFERRED_PROVIDER_virtual/libgles1, ""]
    - [PREFERRED_PROVIDER_virtual/libgles2, "gles-user-module"]
    - [PREFERRED_PROVIDER_virtual/egl, "libegl"]
    - [PREFERRED_PROVIDER_virtual/libgl, ""]
    - [PREFERRED_PROVIDER_virtual/mesa, ""]
    - [PREFERRED_PROVIDER_virtual/libgbm, "libgbm"]
    - [PREFERRED_PROVIDER_libgbm-dev, "libgbm"]
    - [BBMASK, "mesa-gl"]

    # Enable Multimedia features
    - [MACHINE_FEATURES_append, " multimedia"]

    # Add for gstreamer plugins ugly
    - [LICENSE_FLAGS_WHITELIST, "commercial"]

    # Configuration for USB 3.0
    # TODO: Enable this after validation
    #- [MACHINE_FEATURES_append, " usb3"]

    # for mmp test program
    - [DISTRO_FEATURES_append, " mm-test"]

    # Add Capacity Aware migration Strategy (CAS)
    - [MACHINE_FEATURES_append, " cas"]

    # Remove ptest to reduce the build time
    - [DISTRO_FEATURES_remove, "ptest"]

    # HACK: force ipk instead of rpm b/c it makes troubles to PVR UM build otherwise
    - [PACKAGE_CLASSES, "package_rpm"]

    # OMX H264 decoder library for Linux (RTM8RC0000ZMD1LQ00JPL3E)
    - [DISTRO_FEATURES_append, " h264dec_lib"]

    # OMX H264 encoder library for Linux (RTM8RC0000ZME1LQ00JPL3E)
    - [DISTRO_FEATURES_append, " h264enc_lib"]

    # OMX AAC-LC decoder library for Linux (RTM8RC0000ZND1LQ00JPL3E),
    # AAC-LC 2ch decoder middleware library for Linux (RTM8RC0000ZAD1LQ00JPL3E)
    - [DISTRO_FEATURES_append, " aaclcdec_lib"]
    - [DISTRO_FEATURES_append, " aaclcdec_mdw"]

    # Configuration for ivi-shell and ivi-extension
    - [DISTRO_FEATURES_append, " ivi-shell"]

    # Reproducible Builds
    # Set Timestamps at the build start
    - [SOURCE_DATE_EPOCH, "${@time.strftime('%s', time.localtime())}"]
    #- [REPRODUCIBLE_TIMESTAMP_ROOTFS. "${@time.strftime('%s', time.localtime())}"]

    # Skip QoS in case of community Yocto BSP
    - [IMAGE_INSTALL_remove, " kernel-module-qos qosif-user-module qosif-tp-user-module"]

    # For virtualization
    - [DISTRO_FEATURES_append, " virtualization"]

    # Configuration for Para-virtual camera
    - [DISTRO_FEATURES_append, " pvcamera"]

    - [DISTRO_FEATURES_remove, " x11 gtk gobject-introspection-data nfc irda zeroconf 3g"]

    # Remove multimedia options if XT_RCAR_PROPRIETARY_MULTIMEDIA_DIR is not defined
    - [DISTRO_FEATURES_remove, " ${@bb.utils.contains('XT_RCAR_PROPRIETARY_MULTIMEDIA_DIR','','','mm-test', d)}"]
    - [DISTRO_FEATURES_remove, " ${@bb.utils.contains('XT_RCAR_PROPRIETARY_MULTIMEDIA_DIR','','','h264dec_lib', d)}"]
    - [DISTRO_FEATURES_remove, " ${@bb.utils.contains('XT_RCAR_PROPRIETARY_MULTIMEDIA_DIR','','','h264enc_lib', d)}"]
    - [DISTRO_FEATURES_remove, " ${@bb.utils.contains('XT_RCAR_PROPRIETARY_MULTIMEDIA_DIR','','','aaclcdec_lib', d)}"]
    - [DISTRO_FEATURES_remove, " ${@bb.utils.contains('XT_RCAR_PROPRIETARY_MULTIMEDIA_DIR','','','aaclcdec_mdw', d)}"]
    - [DISTRO_FEATURES_remove, " ${@bb.utils.contains('XT_RCAR_PROPRIETARY_MULTIMEDIA_DIR','','','use_eva_pkg', d)}"]

    - [ASSUME_PROVIDED_append, "sync-native"]
    - [HOSTTOOLS_append, " sync"]
    - [ASSUME_PROVIDED_append, "bison-native"]
    - [HOSTTOOLS_append, " bison"]

  # The same set of layers and configs is used both in DomD and DomU
  # to build a DDK from source code
  ddk_source_overrides: &DDK_SOURCE_OVERRIDES
    sources:
      - type: git
        url: "git://git.openembedded.org/meta-python2"
        rev: c96cfe30701ba191903c5f7d560c3ba667d46c9d
      - type: git
        url: "git://github.com/kraj/meta-clang"
        rev: e63d6f9abba5348e2183089d6ef5ea384d7ae8d8
      - type: git
        url: "ssh://git@gitpct.epam.com/epmd-aepr/img-proprietary"
        rev: "ef1aa566d74a11c4d2ae9592474030a706b4cf39"
        dir: "proprietary"
    builder:
      conf:
        - [GLES_VERSION, "1.11"]
        - [PREFERRED_PROVIDER_gles-user-module,          "gles-user-module"]
        - [PREFERRED_VERSION_gles-user-module,           "${GLES_VERSION}"]
        - [PREFERRED_PROVIDER_kernel-module-gles,        "kernel-module-gles"]
        - [PREFERRED_VERSION_kernel-module-gles,         "${GLES_VERSION}"]
        - [PREFERRED_PROVIDER_gles-module-egl-headers,   "gles-module-egl-headers"]
        - [PREFERRED_VERSION_gles-module-egl-headers,    "${GLES_VERSION}"]
      layers:
        - "../meta-python2"
        - "../meta-clang"

components:
  dom0:
    build-dir: "%{YOCTOS_WORK_DIR}"
    default: true
    sources:
      - *COMMON_SOURCES
      - type: git
        url: "git://git.yoctoproject.org/poky.git"
        rev: "424296bf9bb4bae27febf91bce0118df09ce5fa1"
      - type: git
        url: "git://git.yoctoproject.org/meta-virtualization.git"
        rev: "92cd3467502bd27b98a76862ca6525ce425a8479"
      - type: git
        url: "git://git.yoctoproject.org/meta-arm.git"
        rev: "f7c5e7d5094f65d105d9d580ba59527c25fb0d0f"
      - type: git
        url: "git://git.openembedded.org/meta-openembedded"
        rev: "f2d02cb71eaff8eb285a1997b30be52486c160ae"
  domd:
    build-dir: "%{YOCTOS_WORK_DIR}"
    sources:
      - *COMMON_SOURCES
      - type: git
        url: "git://git.yoctoproject.org/poky.git"
        rev: "424296bf9bb4bae27febf91bce0118df09ce5fa1"
      - type: git
        url: "https://github.com/renesas-rcar/meta-renesas.git"
        rev: "fd8ab2bb1b5ca98483c6f4aecf09a85c4d6bc016"
      - type: git
        url: "git://git.yoctoproject.org/meta-selinux.git"
        rev: "7af62c91d7d00a260cf28e7908955539304d100d"
      - type: git
        url: "git://git.yoctoproject.org/meta-virtualization.git"
        rev: "92cd3467502bd27b98a76862ca6525ce425a8479"
      - type: git
        url: "git://git.yoctoproject.org/meta-arm.git"
        rev: "f7c5e7d5094f65d105d9d580ba59527c25fb0d0f"
      - type: git
        url: "git://git.openembedded.org/meta-openembedded"
        rev: "f2d02cb71eaff8eb285a1997b30be52486c160ae"
      - type: git
        url: "git://github.com/CogentEmbedded/meta-rcar.git"
        rev: "a99eb54e9b068375b306fec53f1530f7eb780014"
      - type: git
        url: "git://github.com/iusyk/meta-qt5" 
        rev: "moulin-cr7"
      - type: git
        url: "ssh://git@gitpct.epam.com/epmd-aepr/meta-aos"
        rev: "da4f35734fd6dc4053153aeaa7faa33dfc322f4a"
      - type: git
        url: "ssh://git@gitpct.epam.com/rec-inv/meta-xt-prod-cr7-android-demo.git"
        rev: "feature/cr7-moulim"
    builder:
      type: yocto
      work_dir: "%{DOMD_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - *DOMD_DOMU_CONF
        - [XT_DOM_NAME, "domd"]
        - [XT_OP_TEE_FLAVOUR, "%{XT_OP_TEE_FLAVOUR}"]
        - [BBMASK_append, " meta-arm/meta-arm/recipes-security/optee"]
        - [XT_GUESTS_INSTAL, " "]
      build_target: core-image-weston
      layers:
        - "../poky/meta"
        - "../poky/meta-poky"
        - "../poky/meta-yocto-bsp"
        - "../meta-renesas/meta-rcar-gen3"
        - "../meta-arm/meta-arm-toolchain"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-networking"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-selinux"
        - "../meta-virtualization"
        - "../meta-clang"
        - "../meta-python2"
        - "../meta-qt5"
        - "../meta-xt-common/meta-xt-domx"
        - "../meta-xt-common/meta-xt-driver-domain"
        - "../meta-xt-common/meta-xt-images-vgpu"
        - "../meta-xt-prod-cr7-android-demo/meta-xt-prod-cr7-demo-domx"
        - "../meta-xt-prod-cr7-android-demo/meta-xt-prod-cr7-demo-driver-domain"
      target_images:
        - "tmp/deploy/images/%{MACHINE}/Image"

parameters:
  # Machines
  MACHINE:
    desc: "RCAR Gen3-based device"
    salvator-x-m3:
      default: true
      overrides:
        variables:
          MACHINE: "salvator-x"
          SOC_FAMILY: "r8a7796"
          XT_DOMD_CONFIG_NAME: "domd-salvator-x-m3.cfg"
          XT_DOMU_CONFIG_NAME: "domu-salvator-x-m3.cfg"
          # We can't use %{SOC_FAMILY} because Renesas adds one more digit
          # to it when creating DTB file names
          XT_DOMD_DTB_NAME: "r8a77960-%{MACHINE}-domd.dtb"
    salvator-xs-m3-2x4g:
      default: true
      overrides:
        variables:
          MACHINE: "salvator-x"
          SOC_FAMILY: "r8a7796"
          XT_DOMD_CONFIG_NAME: "domd-salvator-xs-m3-2x4g.cfg"
          XT_DOMU_CONFIG_NAME: "domu-generic-m3-2x4g.cfg"
          XT_DOMD_DTB_NAME: "r8a77961-salvator-xs-2x4g-domd.dtb"
          XT_OP_TEE_FLAVOUR: "salvator_m3_2x4g"
    salvator-xs-h3:
      overrides:
        variables:
          MACHINE: "salvator-x"
          SOC_FAMILY: "r8a7795"
          XT_DOMD_CONFIG_NAME: "domd-salvator-xs-h3.cfg"
    h3ulcb-4x2g-ab:
      overrides:
        variables:
           MACHINE: "h3ulcb-4x2g-ab"
           SOC_FAMILY: "r8a7795"
           XT_DOMD_CONFIG_NAME: "domd-h3ulcb-4x2g-ab.cfg"

  ENABLE_MM:
    desc: "Enable Multimedia support"
    "no":
      default: true
      overrides:
        components:
          domd:
            builder:
              conf:
                # Mask MMP recipes
                - [BBMASK_append, "|kernel-module-uvcs-drv|omx-user-module"]
  PREBUILT_DDK:
    desc: "Use pre-built GPU drivers"
    "no":
      default: true
      overrides:
        components:
          domd:
            *DDK_SOURCE_OVERRIDES
